---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    # - protocol: "TCP"
    - name: http
      # Port accessible inside cluster
      port: 3002
      # Port to forward to inside the pod
  #     targetPort: 3000
  #     # Port accessible outside cluster
  #     nodePort: 30002
  # type: LoadBalancer
 
 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: orenda15/frontend:b0cb01411ba425f247fe74b7607bf20daf8ef8e5
        ports:
        - containerPort: 3002

