language: node_js
node_js: 10.16
before-install:
  - cd APIgateway
install:
  - npm install
script: 
    - echo "test api api_gateway"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPOSITORY=michheta15/api_gateway
  - export TAG=`if [ "$BRANCH" == "api_gateway" ]; then echo "latest"; else echo $BRANCH ; fi`
  - docker build -t api_gateway .
  - docker tag api_gateway $REPOSITORY:$TAG
  - docker push $REPOSITORY:$TAG

branches:
  only:
  - dockerizeApiGateway

