language: node_js
node_js: 10.16
before-install:
  - cd APIgateway
install:
  - npm install
script: 
    - echo "test api api_gateway"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
  - export REPOSITORY=api_gateway
  - export TAG=`if [ "$BRANCH" == "api_gateway" ]; then echo "latest"; else echo $BRANCH ; fi`
  - docker build -t $DOCKER_USERNAME/$REPOSITORY:$TAG .
  - docker push $DOCKER_USERNAME/$REPOSITORY:$TAG

branches:
  only:
  - dockerizeApiGateway

