language: node_js
node_js: 10.16
before-install:
  - cd APIgateway
install:
  - npm install
script: 
    - echo "test api_gateway"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t orenda15/api_gateway:latest .
  - docker push orenda15/api_gateway:latest

branches:
  only:
  - dockerizeApiGateway

