language: node_js
node_js: 10.16
before-install:
  - cd userManagement
install:
  - npm install
script: 
    - echo "test user_management"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t orenda15/user_management:latest .
  - docker push orenda15/user_management:latest
branches:
  only:
  - dockerizeUserManagement