language: node_js
node_js: 10.16
before-install:
  - cd sessionManagement
install:
  - npm install
script: 
   - npm test 
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t orenda15/session_management:latest .
  - docker push orenda15/session_management:latest
branches:
  only:
  - dockerizeSessionManagement
  
