language: node_js
node_js: 10.16
before-install:
  - cd APIgateway
install:
  - npm install
script: 
    - echo "test api api_gateway"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPOSITORY=michheta15/api_gateway
  - export TAG=`if [ "$TRAVIS_BRANCH" == "dockerizeApiGateway" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t orenda_api_gateway .
  - docker tag data-retrieval-microservice $REPOSITORY:$TAG
  - docker push michheta15/api_gateway:orenda_api_gateway

branches:
  only:
  - dockerizeApiGateway

