
language: python
python: 3.7
before-install:
  - cd dataModelling
install:
  - pip3 install -r requirements.txt
script:
  #- python3 app.py
  - echo "test dataRetrieval"

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t orenda15/user_management:latest .
  - docker push orenda15/user_management:latest
branches:
  only:
  - dockerizeDataModelling