language: node_js
node_js: 10.16
before-install:
  - cd frontend
install:
  - npm install
script: 
    - echo "test frontend"
#   - npm start
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t michheta15/frontend:latest .
  - docker push michheta15/frontend:latest
branches:
  only:
  - dockerizeFrontend
  
