language: java
jdk: openjdk8
java: 8
before-script:
  - cd data_analysis
script:
  - mvn install
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t orenda15/data_analysis:latest .
  - docker push orenda15/data_analysis:latest
branches:
  only:
  - dockerizeDataAnalysis
  
