version: "3"
services:
  data_retrieval:
    build: "./dataRetrieval"
    networks:
        - kafka_orenda
    container_name: data-retrieval-service

networks:
    kafka_orenda:
        external: true
