version: "3"
services:
  user_management:
    container_name: UserManagementService
    build: "./userManagement"
    networks:
      - kafka_orenda
    ports:
      - "5009:5009"
    external_links:
      - frontendService
networks:
  kafka_orenda:
    external: true
