version: "3"
services:
  data_retrieval:
    container_name: data-retrieval-service
    build: "./dataRetrieval"
    networks:
        - kafka_orenda
networks:
    kafka_orenda:
        external: true
