version: "3"
services:      
  zookeeper:
    image: wurstmeister/zookeeper:latest
   # container_name: zookeeper_service
    ports:
      - "2181:2181"
    networks:
      - kafka_orenda
  kafka:
  #  container_name: kafka_service
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    networks:
      - kafka_orenda
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "
        test:1:1,
        apiGatewayConsumerF:1:1,
        dataRetrievalConsumerF:1:1,
        dataModellingConsumerF:1:1,
        dataAnalysisConsumerF:1:1,
        sessionManagementConsumerF:1:1,
        sessionManagementConsumerApiF:1:1,
        "
  data_analysis:
   # container_name: data-analysis_service
    build: "./data_analysis"
    ports:
      - "3002:3002"
    networks: 
      - kafka_orenda
    depends_on:
      - kafka
networks:
 # orenda:
  kafka_orenda:
    external: true
