version: "3"
services:
  session_management:
    container_name: session_management_service
    build: "./SessionManagement"
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - api_gateway

