version: "3"
services:
  session_management:
    container_name: session-management-service
    build: "./SessionManagement"
    networks:
      - kafka_orenda
    depends_on:
      - kafka
networks:
  kafka_orenda:
    external: true

