version: "3"
services:
  api_gateway:
    container_name: apiGatewayService
    build: "./APIGateway"
    networks:
      - kafka_orenda
    ports:
      - "5000:5000"
    external_links:
      - kafkaService
      - zookeeperService
networks:
  kafka_orenda:
    external: true
