# docker-compose.yml

version: "3"
services:
version: "3"
services:  
  data_modelling:
    build: "./dataModelling"
    networks:
        - kafka_orenda
networks:
    kafka_orenda:
        external: true


