version: "3"
services:
  frontend:
    container_name: frontend_service
    build: "./frontend"
    ports:
      - "3000:3000"
    external_links:
      - apiGatewayService
      - userManagmentService

