version: "3"
services:
  api_gateway:
    container_name: api-gateway-service
    build: "./APIGateway"
    networks:
      - kafka_orenda
    ports:
      - "5000:5000"
networks:
  kafka_orenda:
    external: true
