version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-service
    ports:
      - "2181:2181"
    networks:
      - orenda
  kafka:
    container_name: kafka-service
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    networks:
      - orenda
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka:9090,\
        EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9090,\
        EXTERNAL://kafka-service:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,\
        EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "
        test:1:1,
        apiGatewayConsumerF:1:1,
        dataRetrievalConsumerF:1:1,
        dataModellingConsumerF:1:1,
        dataAnalysisConsumerF:1:1,
        sessionManagementConsumerF:1:1,
        sessionManagementConsumerApiF:1:1,
        "
networks:
  orenda:
