version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeperService
    ports:
      - "2181:2181"
    networks:
      - orenda_default
  kafka:
    container_name: kafkaService
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    networks:
      - orenda_default
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "
        test:1:1,
        apiGatewayConsumerF:1:1,
        dataRetrievalConsumerF:1:1,
        dataModellingConsumerF:1:1,
        dataAnalysisConsumerF:1:1,
        sessionManagementConsumerF:1:1,
        sessionManagementConsumerApiF:1:1,
        "
networks:
  orenda_default:
    external: true
